name:                servant-acl
version:             0.1.0.0
github:              "jkarni/servant-acl"
license:             BSD3
author:              "Julian K. Arni"
maintainer:          "jkarni@gmail.com"
copyright:           "2021 Artificial Labs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jkarni/servant-acl#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- mtl
- network-uri
- network-uri-json
- servant
- servant-server
- text
- unordered-containers

library:
  source-dirs: src
  # We don't want this to be a top-level extension because the README should
  # have no extensions at all.
  default-extensions: &many-extensions
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - DerivingStrategies
    - ExistentialQuantification
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - KindSignatures
    - MultiParamTypeClasses
    - OverloadedStrings
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeFamilies
    - TypeOperators

tests:

  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-qq
    - servant-acl
    - hspec
    default-extensions: *many-extensions


executables:
  readme:
    main: examples/README.lhs
    ghc-options:
    - -pgmL markdown-unlit
    dependencies:
    - markdown-unlit
    - mtl
    - servant-acl
    - servant-auth
    - servant-auth-server
    - warp



ghc-options:
  - -Wall
